# Generated by Django 5.2.6 on 2025-12-01 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_suggested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='user_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Environment_user_FK', to=settings.AUTH_USER_MODEL),
        ),
    ]
